src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
#[ORM\Table(name: 'tickets')]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $closed = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $created_timestamp = null;

    #[ORM\Column(name: 'fk_userId', type: Types::BIGINT)]
    private ?string $fk_userId = null;

    private ?User $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isClosed(): ?bool
    {
        return $this->closed;
    }

    public function isClosedString(): ?string
    {
        return $this->closed ? 'Closed' : 'Open';
    }

    public function setClosed(bool $closed): self
    {
        $this->closed = $closed;

        return $this;
    }

    public function getCreatedTimestamp(): ?string
    {
        return $this->created_timestamp;
    }

    public function setCreatedTimestamp(string $created_timestamp): self
    {
        $this->created_timestamp = $created_timestamp;

        return $this;
    }

    public function getFkUserId(): ?string
    {
        return $this->fk_userId;
    }

    public function setFkUserId(string $fk_userId): self
    {
        $this->fk_userId = $fk_userId;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Review;
use App\Entity\Ticket;
use App\Entity\TicketMessage;
use App\Entity\User;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TicketController extends AbstractController
{
    private RequestStack $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    #[Route('/tickets', name: 'tickets', methods: ['GET', 'HEAD'])]
    public function index(ManagerRegistry $doctrine): Response
    {
        if(!$this->requestStack->getSession()->get('logged_in')) {
            return $this->redirectToRoute('login');
        }

        return $this->renderTickets($doctrine);
    }

    #[Route('/ticket/message/create', name: 'ticket_message_create', methods: ['POST'])]
    public function ticketMessageCreate(Request $request, ManagerRegistry $doctrine): Response
    {
        if(!$this->requestStack->getSession()->get('logged_in')) {
            return $this->redirectToRoute('login');
        }

        $userID = $this->requestStack->getSession()->get('user_id');

        $message = new Message();

        $content = $request->request->get('content');

        if(empty($content)) {
            $this->addFlash('error', 'Message cannot be empty.');

            return $this->redirect('/tickets/view/' . $request->request->get('ticket_id'));
        }

        $message
            ->setContent($content)
            ->setFkUserId($userID)
            ->setCreatedTimestamp(date('Y-m-d H:i:s'));

        $entityManager = $doctrine->getManager();

        $entityManager->persist($message);
        $entityManager->flush();

        $ticketMessage = new TicketMessage();

        $ticketMessage
            ->setFkMessageId($message->getId())
            ->setFkTicketId($request->request->get('ticket_id'));

        $entityManager->persist($ticketMessage);
        $entityManager->flush();

        $this->addFlash('info', 'Message created successfully.');

        return $this->redirect('/tickets/view/' . $request->request->get('ticket_id'));
    }

    #[Route('/tickets/view/{id}', name: 'ticket_view', methods: ['GET', 'HEAD'])]
    public function ticketView($id, ManagerRegistry $doctrine): Response
    {
        if(!$this->requestStack->getSession()->get('logged_in')) {
            return $this->redirectToRoute('login');
        }

        $userRepository = $doctrine->getRepository(User::class);

        $ticketRepository = $doctrine->getRepository(Ticket::class);

        $ticket = $ticketRepository->find($id);

        $userID = $this->requestStack->getSession()->get('user_id');

        if(!$this->requestStack->getSession()->get('admin') && $ticket->getFkUserId() != $userID) {
            return $this->redirectToRoute('tickets');
        }

        $ticketMessageRepository = $doctrine->getRepository(TicketMessage::class);

        $ticketMessages = $ticketMessageRepository->findBy(
            ['fk_ticketId' => $id]
        );

        $messageRepository = $doctrine->getRepository(Message::class);

        $messages = [];

        foreach($ticketMessages as $ticketMessage) {
            $message = $messageRepository->find($ticketMessage->getFkMessageId());
            $user = $userRepository->find($message->getFkUserId());
            $message->setUser($user);
            $messages[] = $message;
        }

        usort($messages, function($a, $b) {
            return strtotime($b->getCreatedTimestamp()) - strtotime($a->getCreatedTimestamp());
        });

        return $this->render('ticket/view.html.twig', [
            'logged_in' => $this->requestStack->getSession()->get('logged_in'),
            'admin' => $this->requestStack->getSession()->get('admin'),
            'user' => $this->requestStack->getSession()->get('user'),
            'ticket' => $ticket,
            'messages' => $messages
        ]);
    }


    #[Route('/tickets/create', name: 'tickets_create', methods: ['POST'])]
    public function ticketsCreatePost(Request $request, ManagerRegistry $doctrine): Response
    {
        if(!$this->requestStack->getSession()->get('logged_in')) {
            return $this->redirectToRoute('login');
        }

        $userID = $this->requestStack->getSession()->get('user_id');

        $ticket = new Ticket();

        $title = $request->request->get('ticket_title');
        $description = $request->request->get('ticket_description');

        if(empty($title)) {
            $this->addFlash('error', 'Subject field should be filled.');

            return $this->redirectToRoute('tickets');
        }

        if(empty($description)) {
            $this->addFlash('error', 'Description field should be filled.');

            return $this->redirectToRoute('tickets');
        }

        $ticket->setFkUserId($userID)
            ->setTitle($title)
            ->setDescription($description)
            ->setClosed(false)
            ->setCreatedTimestamp(date('Y-m-d H:i:s'));

        $entityManager = $doctrine->getManager();

        $entityManager->persist($ticket);

        $entityManager->flush();

        $this->addFlash('info', 'Ticket created successfully.');

        return $this->renderTickets($doctrine);
    }

    #[Route('/ticket/message/delete/{id}', name: 'ticket_message_delete', methods: ['POST'])]
    public function reviewDelete($id, Request $request, ManagerRegistry $doctrine): Response
    {
        $ticketID = $request->request->get('ticket_id');

        if(!$this->requestStack->getSession()->get('admin')) {
            return $this->redirectToRoute('ticket_view', [
                'ticketId' => $ticketID
            ]);
        }

        $ticketMessageRepository = $doctrine->getRepository(TicketMessage::class);

        $ticketMessage = $ticketMessageRepository->findByMessageId($id);

        $entityManager = $doctrine->getManager();

        $entityManager->remove($ticketMessage[0]);

        $entityManager->flush();

        $messageRepository = $doctrine->getRepository(Message::class);

        $message = $messageRepository->find($id);

        $entityManager->remove($message);

        $entityManager->flush();

        return $this->redirectToRoute('ticket_view', [
            'ticketId' => $ticketID
        ]);
    }


    #[Route('/ticket/delete/{id}', name: 'ticket_delete', methods: ['POST'])]
    public function ticketDelete($id, Request $request, ManagerRegistry $doctrine): Response
    {
        if(!$this->requestStack->getSession()->get('admin')) {
            return $this->redirectToRoute('tickets');
        }

        $ticketRepository = $doctrine->getRepository(Ticket::class);

        $ticketMessageRepository = $doctrine->getRepository(TicketMessage::class);

        $messageRepository = $doctrine->getRepository(Message::class);

        $ticket = $ticketRepository->find($id);

        if(is_null($ticket)) {
            return $this->redirectToRoute('admin_tickets');
        }

        $ticketMessages = $ticketMessageRepository->findBy(
            ['fk_ticketId' => $id]
        );

        $entityManager = $doctrine->getManager();

        foreach($ticketMessages as $ticketMessage) {
            $message = $messageRepository->find($ticketMessage->getFkMessageId());
            $entityManager->remove($message);
            $entityManager->remove($ticketMessage);

            $entityManager->flush();
        }

        $entityManager->remove($ticket);

        $entityManager->flush();

        return $this->redirectToRoute('tickets');
    }

    #[Route('/ticket/close/{id}', name: 'ticket_close', methods: ['POST'])]
    public function ticketClose($id, ManagerRegistry $doctrine): Response
    {
        $ticketRepository = $doctrine->getRepository(Ticket::class);

        $ticket = $ticketRepository->find($id);

        if(is_null($ticket)) {
            return $this->redirectToRoute('ticket_view', [
                'ticketId' => $id
            ]);
        }

        $ticket->setClosed(true);

        $entityManager = $doctrine->getManager();

        $entityManager->persist($ticket);

        $entityManager->flush();

        return $this->redirectToRoute('tickets');
    }

    /**
     * @param ManagerRegistry $doctrine
     * @return Response
     */
    public function renderTickets(ManagerRegistry $doctrine): Response
    {
        $ticketRepository = $doctrine->getRepository(Ticket::class);

        $userID = $this->requestStack->getSession()->get('user_id');

        $tickets = $ticketRepository->findBy(
            ['fk_userId' => $userID],
            ['created_timestamp' => 'DESC']
        );

        return $this->render('ticket/index.html.twig', [
            'logged_in' => $this->requestStack->getSession()->get('logged_in'),
            'user' => $this->requestStack->getSession()->get('user'),
            'admin' => $this->requestStack->getSession()->get('admin'),
            'tickets' => $tickets
        ]);
    }
}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modestas K. | Tickets{% endblock %}

{% block javascripts %}
<script>
$(document).ready(function() {
    $('#topic_search').on('input', (e) =>
    {
        const filterable = $('.filterable');

        const value = e.target.value;

        for(let i = 0; i < filterable.length; i++)
        {
            const el = filterable[i];

            const id = el.id.toLowerCase();

            if(value !== '') {
                if(id.includes(value)) {
                    el.style.display = '';
                } else {
                    el.style.display = 'none';
                }
            } else {
                el.style.display = '';
            }
        }
    });
});
</script>
{% endblock %}

{% block body %}
<br>
<div class="container">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-8">
            <div class="card-body p-4 p-md-5">
                <h2 class="h1-responsive font-weight-bold my-4">CREATE A TICKET</h2>
                <p>
                    Create a ticket where we can discuss your project.
                </p>
                <p>
                    I will get back to you as soon as possible.
                </p>

                <form class="px-md-2" method="post" action="{{ path("tickets_create") }}">

                    <div class="form-outline mb-4">
                        <input type="text" id="ticket_title" name="ticket_title" class="form-control" />
                        <label class="form-label" for="ticket_title">Subject</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="text" id="ticket_description" name="ticket_description" class="form-control md-textarea" />
                        <label class="form-label" for="ticket_description">Description</label>
                    </div>

                    <button type="submit" class="btn btn-sm btn-success btn-lg mb-1">Submit</button>
                </form>

                <br>
                <input type="text" id="topic_search" name="topic_search" class="form-control" />
                <label class="form-label" for="topic_search">Search by ticket subject</label>

                <p class="text-muted text-center mb-0 px-md-2 small">You can find your tickets below.</p>
                <p class="text-muted text-center mb-0 px-md-2 small">To view more information, click on the ticket.</p>
            </div>
        </div>

        <div class="col-md-6">
            <div class="list-group">
                {% for ticket in tickets %}
                    <div id="{{ ticket.title }}" class="filterable">
                    <a class="list-group-item list-group-item-action flex-column align-items-start" href="/tickets/view/{{ ticket.id }}">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ ticket.title }}</h5>
                            <small>{{ ticket.createdTimestamp }}</small>
                        </div>
                        <p class="mb-1">{{ ticket.description }}</p>
                        <small>{{ ticket.closedString }}</small>
                    </a>
                    </div>
                    <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/ticket/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ReviewController!{% endblock %}

{% block body %}
<br>
<div class="container">
    <div class="row d-flex justify-content-center align-items-center h-100">

        <div class="col-lg-8">
            <div class="card-body">
                <h3 class="card-title mb-1">{{ ticket.title }}</h3>
                <p class="card-text"><em>{{ ticket.description }}</em></p>

                <p class="card-text"><small class="text-muted">{{ ticket.createdTimestamp }}</small></p>
            </div>
        </div>

        <div class="col-lg-8">
            <div class="card-body p-4 p-md-5">
                <form class="px-md-2" method="post" action="{{ path("ticket_message_create") }}">

                    <div class="form-outline mb-4">
                        <label class="form-label" for="content">Message</label>
                        <input type="text" id="content" name="content" class="form-control md-textarea" />
                    </div>

                    <input type="hidden" id="ticket_id" name="ticket_id" value="{{ ticket.id }}" />

                    <button type="submit" class="btn btn-sm btn-success btn-lg mb-1">Send</button>
                </form>

                <form class="px-md-2" method="post" action="{{ path("ticket_close", {"id": ticket.id }) }}">

                    <input type="hidden" id="ticket_id" name="ticket_id" value="{{ ticket.id }}" />
                    <button type="submit" class="btn btn-sm btn-danger btn-lg mb-1">Close</button>
                </form>

                <p class="text-muted text-center mb-0 px-md-2 small">You can find the previous converstation below.</p>

            </div>
        </div>

        <div class="col-md-8">
            <div class="list-group">
                {% for message in messages %}
                    <a class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ message.user.name }}</h5>
                        </div>
                        <p class="mb-1">{{ message.content }}</p>
                        <small>{{ message.createdTimestamp }}</small>

                        {% if logged_in is defined and logged_in is same as(true) and admin is defined and admin is same as(true) %}
                        <form method="post" action="{{ path("ticket_message_delete", {"id": message.id}) }}">
                            <input type="hidden" id="ticket_id" name="ticket_id" value="{{ ticket.id }}" />

                            <div class="d-grid d-md-flex justify-content-md-end">
                                <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </div>
                        </form>
                        {% endif %}
                    </a>
                    <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}